# Generated by Django 4.1.2 on 2022-11-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название экскурсии')),
                ('imgs', models.ImageField(blank=True, upload_to='place_images', verbose_name='Картинки с экскурсии')),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Полное описание')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота/Longitude')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта/Latitude')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'db_table': 'place',
            },
        ),
    ]
