# Generated by Django 4.1.2 on 2022-11-04 11:50

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [migrations.RemoveField(
      model_name='place',
      name='imgs',
    ),
    ]
