# Generated by Django 4.1.2 on 2022-11-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options_image_title_alter_image_table'),
    ]

    operations = [migrations.RemoveField(
      model_name='image',
      name='title',
    ),
    ]
