# Generated by Django 4.1.2 on 2022-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20221104_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер картинки'),
        ),
    ]
