# Generated by Django 4.1.2 on 2022-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_image_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imgs',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to='place_images', verbose_name='Картинка с экскурсии'),
        ),
    ]
