# Generated by Django 4.1.2 on 2022-11-06 15:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description_long1',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
    ]
