# Generated by Django 4.1 on 2022-11-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_description_long1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='place_images', verbose_name='Картинка с экскурсии'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='Широта/Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(verbose_name='Долгота/Longitude'),
        ),
    ]
